In [1]:
import numpy as np
from numpy.linalg import inv, det

# Determinant of a Matrix (행렬식)

Inverse Matrix를 구하기 위해서는 먼저 determinant 구할줄 알아야 합니다.

### Symbol 

$ | \mathbf{A} | $는 determinant of the matrix $ \mathbf{A} $를 가르킵니다.<br>
(absolute 기호와 동일)

### $$ | \mathbf{A} | $$

### Calculating the Determinant

* 반드시 matrix는 square (정사각형.. ) 이어야 합니다.

### 2 x 2 Matrix 

$$ \textit{A} = \begin{bmatrix}a & b\\c & d\end{bmatrix} $$

$$ |\textit{A}| = ad - bc $$

<img src="images/determinant01.gif" class="img-responsive img-rounded">

In [2]:
A = np.array([[4, 6], [3, 8]], dtype=np.float32)

print 'Matrix A'
print A
print 
print 'The determinant of a Matrix A:', det(A)
print '4*8 - 3*6 = 32 - 18 = 14'

Matrix A
[[ 4.  6.]
 [ 3.  8.]]

The determinant of a Matrix A: 14.0
4*8 - 3*6 = 32 - 18 = 14


### 3 x 3 Matrix 

$$ \textit{A} = \begin{bmatrix}a & b & c\\d & e & f\\g & h & i\end{bmatrix} $$

$$ |\textit{A}| = a(ei - fh) - b(di - fg) + c(dh - eg) $$

<img src="images/determinant02.gif" class="img-responsive img-rounded">

In [3]:
C = np.array([[6,  1,  1], 
              [4, -2,  5], 
              [2,  8,  7]])
print 'Matrix C'
print C
print 
print 'The determinant of a Matrix C:', det(C)

Matrix C
[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]

The determinant of a Matrix C: -306.0


### 4 x 4 Matrix or higher 

$$ \textit{A} = \begin{bmatrix}a & b & c & d\\e & f & g & h \\i & j & k & l \end{bmatrix} $$

* +a... -b... +c... -d. 이런 패턴이 있음
* 첫번째 row의 element를 곱하는데.. 이때 해당 element의 row 그리고 column이 속하지 않은 determinant of the matrix를 구함

<img src="images/determinant03.gif" class="img-responsive img-rounded">

In [ ]:
np.array([])