In [1]:
import numpy as np
from numpy.linalg import inv, det

# Solving Systems of linear equations using Matrix

가령 다음과 같은 systems of lienear equations가 있고, x ,y, z의 값을 알아내고자 합니다.

$$ 
\begin{eqnarray} \\ 
x + y + z = 6 \\ 
2y + 5z = -4 \\
2x + 5y -z = 27 \\
\end{eqnarray} 
$$

공식으로는 다음과 같습니다. 

### $$ \textit{AX = B} $$

* $ \textit{A} $는 known matrix
* $ \textit{B} $는 known vector
* $ \textit{X} $는 a vector of unknown variables 로서.. 문제를 풀어서 값을 알아내야하는 것들입니다.

<img src="images/systems_of_equations01.gif" class="img-responsive img-rounded">

### Matrix Solution

inverse of a Matrix 를 사용해서 문제를 해결할 수 있습니다.

### $$ \mathit{X = A^{-1}B} $$

<img src="images/systems_of_equations02.gif" class="img-responsive img-rounded">

<img src="images/systems_of_equations03.gif" class="img-responsive img-rounded">

In [3]:
A = np.array([[1, 1, 1], [0, 2, 5], [2, 5, -1]])
B = np.array([6, -4, 27])

print '[A]'
print A

print
print '[B]'
print B


[A]
[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]

[B]
[ 6 -4 27]


In [4]:
print 'X의 값은:', inv(A).dot(B)

X의 값은: [ 5.  3. -2.]
